### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by Boryyy** [hannad4/instaFollow#3] opened 2021-04-18 20:51 UTC
hey , like u said last time , yes i need this for a project and if u can help me that would be great , i fixed everything u told me and it works fine , it goes in my profile , goes to followers , does the scan , then stuck at 80% of followers , and it closes itself :|
(i tried doing my own account , not the bot one , still the same )

![image](https://user-images.githubusercontent.com/60760570/115160448-71d21a80-a098-11eb-95e3-4d235596031a.png)

**Comment by hannad4** [comment] 2021-04-18 20:57
I am unable to produce this error. Every account I have tried it on works well.

It would be more helpful if you can provide more details as to what you see beyond just "it doesn't work". What does the browser show when this happens? Did you try running this in debug mode to step through the program and see what the issue is?

if you can let me know what the account is that is being tracked, I can try running it and seeing if I produce the same error.

**Comment by Boryyy** [comment] 2021-04-18 21:36
yea sorry about that , i will give u all the info 


**screenshot when the error happen , it does everything , scan 80% of the followers and then it stucks for like 4 seconds , then closes itself**
![image](https://user-images.githubusercontent.com/60760570/115161540-a648d500-a09e-11eb-89a0-b7e7a47ad8a4.png)


**screenshot of the debugger**
![image](https://user-images.githubusercontent.com/60760570/115161566-c9738480-a09e-11eb-85b7-a6c2c71393ff.png)


**last message before it closes itself , the "...." of the scrolling down in followers**
![image](https://user-images.githubusercontent.com/60760570/115161588-e60fbc80-a09e-11eb-811b-4d00e333974a.png)

**Comment by Boryyy** [comment] 2021-04-18 21:45
maybe it bugs when it checks for followers , and just need a new line just to double check everytime it gets stuck?

**Comment by Boryyy** [comment] 2021-04-18 21:57
and yea thats the problem , when it gets stuck , if i keep scroll myself the program does not crash, i need to do it manually when it gets stuck.

do u have discord so i can send u a video of the full run?

**Comment by hannad4** [comment] 2021-04-18 22:01
what is the total number of followers that the account has?

it seems like the problem is occurring with the way the obtain list function is implemented, and that if it takes too long to grab the list, then the error is raised


if you can tell me which account you are using to test, I can try fixing it on my end. otherwise, I will have to close this issue since I cannot reproduce the error and I'm not actively working on this project anymore anyways

**Comment by Boryyy** [comment] 2021-04-18 22:07
send me ur email or somthing i can send u the whole code , or the username im trying to do?

**Comment by hannad4** [comment] 2021-04-18 22:10
send your program to hannad4@tcnj.edu

**Comment by Boryyy** [comment] 2021-04-18 22:13
done

**Comment by hannad4** [comment] 2021-04-18 22:51
After looking at your code, it seems that the account will need a different method for scraping all the followers you have. I would recommend you try going beyond modifying just this code and try this method (see comment labeled March 2020): 
https://stackoverflow.com/questions/37233803/how-to-web-scrape-followers-from-instagram-web-browser

Or better yet, you can try using [Instaloader](https://instaloader.github.io/) to pull your data, which might be closer to your needs. 

Closing out this issue as I will not be able to help with this problem any more unless I re-write the program for this particular scenario

**Closed as completed by hannad4** 2021-04-18 22:51 UTC
